name = "rssbot-cf-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
TELEGRAM_BOT_TOKEN = "7255646041:AAEDaXVP3v1pP-4DDM3ughuPBNy_tsnQ04M"
ADMIN_USER_ID = "1098918263"

# KV命名空间配置
[[kv_namespaces]]
binding = "RSS_DB"
id = "2d3deca4802d462fab1ce54a39011023"
preview_id = "09b5a7c9875d4d53acaabc5eacf84c98"

# 定时任务 - 每分钟检查RSS更新
[triggers]
crons = ["* * * * *"] 